apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pregod-indexer
  namespace: pregod
spec:
  maxReplicas: 20
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pregod-indexer
  targetCPUUtilizationPercentage: 70
